# Generated by Django 3.2 on 2023-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
