# Generated by Django 3.2 on 2023-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230905_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.PositiveBigIntegerField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
