# Generated by Django 3.2 on 2023-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
