# Generated by Django 3.2 on 2023-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230906_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
