# Generated by Django 3.2 on 2023-09-24 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('TOP TIPS', 'TOP TIPS'), ('NEW IN', 'NEW IN'), ('HOW TO', 'HOW TO'), ('MASKS', 'MASKS'), ('SUNCARE', 'SUNCARE'), ('BESTSELLERS', 'BESTSELLERS')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.CharField(choices=[('POPULAR', 'POPULAR'), ('RECENT', 'RECENT')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
