# Generated by Django 3.2 on 2023-09-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uptade_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uptade_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uptade_at',
            new_name='updated_at',
        ),
    ]
