# Generated by Django 3.2 on 2023-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_name_skintype_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
