# Generated by Django 3.2 on 2023-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20230922_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvv',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
    ]
