# Generated by Django 3.2 on 2023-12-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkinType',
        ),
    ]
